### ISSUE TITLE
How to refine the obtained grasps?

### ISSUE THREAD

**Issue by dulucas** [contactgrasp/dart#1]
Hi,

If I understand correctly, to refine the generated grasps, I need to use the code `dart/build/grasp_analyzer` with parameter setted as `no_analysis`, and click the boutton `init` to initialize a grasping pose then continue to click `iterate` to refine the pose, right?

Is there a way to get the refined poses?

And usually how many iterations is needed for each grasping pose? Is there a way to refine the poses without using graphical interface?

Thx!

**Comment by samarth-robo** [comment]
You mean a way to save the refined pose? There should be a "save GT" button or something like that.

That binary has 2 modes:
- If you don't give the "no_analysis" commandline argument it automatically analyzes all the grasps in the initialization file one by one, and saves their refined grasps. By "analyzes" I mean: arrange the hand in the initial pose, do iterations till the convergence criteria are met, save the result. See the terminal output for where it saves the refined grasps.
- If you give the "no_analysis" commandline argument, it just loads the hand and object in the initial pose and waits for user interaction. Here you can click the "iterate" button as many times as you want (1 click = 1 iteration of refinement), and then click the "save GT" button to save the refinement result. The number of iterations required depends on the initialization.

**Comment by dulucas** [comment]
OK thanks a lot! For the number of iterations, I current use the ContactGrasp as a baseline for grasps generation, so I need a number of iterations for all the objects, do you have an idea of this?
